// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8g93i1xvqpolP_1jdFy3RyiQ-Xu2sW_g',
    appId: '1:1088858633283:web:304ad83134fed8f7ac90f6',
    messagingSenderId: '1088858633283',
    projectId: 'stockhive-elvara',
    authDomain: 'stockhive-elvara.firebaseapp.com',
    storageBucket: 'stockhive-elvara.firebasestorage.app',
    measurementId: 'G-MD2223LTQM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb9qdjuU5QwAZGKj2JYHAT6Kux-6QlbQk',
    appId: '1:1088858633283:android:d17afc679039d0e0ac90f6',
    messagingSenderId: '1088858633283',
    projectId: 'stockhive-elvara',
    storageBucket: 'stockhive-elvara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAenaP__kHqXW1CMfpbHLb0CZHVPYVuOtM',
    appId: '1:1088858633283:ios:575ab927ebc43271ac90f6',
    messagingSenderId: '1088858633283',
    projectId: 'stockhive-elvara',
    storageBucket: 'stockhive-elvara.firebasestorage.app',
    iosBundleId: 'com.example.stockHive',
  );
}
